Add controllers
ebogacheva/java-shareit pull request #1
Opened 2023-05-22 19:14 UTC by ebogacheva

2023-05-23 16:50 UTC, Fleaman777 requested changes

2023-05-23 16:50 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item create(@RequestHeader("X-Sharer-User-Id") long userId,
X-Sharer-User-Id - можно вынеси в константу

2023-05-23 16:50 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +    private final HashMap<Long, Item> items = new HashMap<>();
если тип сделать более широким Map, то полифорфизм будет работать лучше

2023-05-23 16:50 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +                    })
для улучшения читаемости логику внутри filter так же можно вынести в отдельный метод

2023-05-23 16:50 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        } else throw new ShareItElementNotFoundException("Item not found.");
у Optional есть удобный метод .orElseThrow(), 
который поможет сократить этот и др похожиме методы

2023-05-23 16:50 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    private UserServiceImpl userService;
если поле объявить final и добавить аннотацию @RequiredArgsConstructor, 
то явно не надо будет вешать аннотацию @Autowire

2023-05-23 22:16 UTC, ebogacheva commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item create(@RequestHeader("X-Sharer-User-Id") long userId,
Сделала.

2023-05-23 22:16 UTC, ebogacheva commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +    private final HashMap<Long, Item> items = new HashMap<>();
Сделала.

2023-05-23 22:16 UTC, ebogacheva commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +                    })
Сделала.

2023-05-23 22:16 UTC, ebogacheva commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        } else throw new ShareItElementNotFoundException("Item not found.");
Переделала.

2023-05-23 22:16 UTC, ebogacheva commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    private UserServiceImpl userService;
Сделала. Не понимаю, почему так лучше(((

2023-05-24 16:07 UTC, Fleaman777 approved these changes

2023-05-24 19:17 UTC, merged