Add bookings
ebogacheva/java-shareit pull request #2
Opened 2023-06-13 21:14 UTC by ebogacheva

2023-06-14 21:00 UTC, Fleaman777 requested changes

2023-06-14 21:00 UTC, Fleaman777 commented on pom.xml
> +			<artifactId>hibernate-core</artifactId>
мне кажется не обязательно добавлять эту зависимость, т.к. в spring-boot-starter-data-jpa она скорей всего есть,

2023-06-14 21:00 UTC, Fleaman777 commented on pom.xml
>  	</dependencies>
так же не увидел зависимость на postgresql драйвер, который должен использоваться в этом спринте

2023-06-14 21:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingFullDto update(@RequestHeader("X-Sharer-User-Id") long userId,
вместо X-Sharer-User-Id можно использовать соответствующую константу

аналагично в др местах

2023-06-14 21:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        getUserIfExists(userId);
проверку юзера можно было бы немного сдвинуть, и сделать ее перед searchCondition,
что позволит немного оптимизировать работу метода

2023-06-14 21:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public BookingFullDto create(BookingInputDto bookingInputDto, Long userId) {
метод изменяет состояние БД, правильней было бы его выполнять в транзакции, 

относится ко всем аналогичным местам

2023-06-14 21:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (booking.getStatus().equals(BookingStatus.APPROVED)) {
енамы хорошо сравнивать через == 
так и сравнивается быстрее, и выглядит чуть очевидней

аналагично в др местах

2023-06-14 21:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            }
енам не должен выполнять такую логику(обращение к бд), по сути, это просто статические константы, в зависимости от которых в основных сервисах будет выполнятся какая-та логика. 

а сейчас получается, что эти константы содержат логику, которая зависит от другого компонента(репозиторий), что архитектурно не правильно, т.к. получается, что статический контекст(контекст класса) зависит от экземплярного контекста(контекст объекта)

2023-06-14 21:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        public abstract List<Booking> getUserBookings(BookingRepository repository, Long userId);
соответсвенно этих абстрактных методоа не должно быть. 

В итоге, енам будет содержать просто разные значения(WAITING, REJECTED....) в зависимости от которых в методе сервиса будет выполнятся соответствующая логика

2023-06-14 21:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        public abstract List<Booking> getUserItemsBookings(BookingRepository repository, Long userId);
есть еще такое объяснение от chatGPT, почему в енаме плохо иметь внешнюю зависимость, 
с ним я так же согласен

From a structural and architectural standpoint, having enum instances with methods that use an external dependency (such as a repository class) can introduce coupling between the enum and the repository. This coupling may not adhere to certain principles of clean architecture or separation of concerns.

Ideally, enums should represent a fixed set of values or constants, and their methods should primarily operate on those values without relying on external dependencies. This helps maintain the encapsulation and single responsibility principle for enum instances.

To decouple the enum from the repository, one approach is to pass the required data or dependencies as parameters to the enum methods instead of directly referencing the repository. This way, the enum instances can remain independent of the specific implementation details and dependencies.

However, it's worth noting that the impact of this coupling depends on the overall design and requirements of the system. If the enum's usage and coupling with the repository are limited and do not introduce significant complexity or maintainability concerns, it might be acceptable in certain cases. As always, it's essential to consider the trade-offs and make design decisions based on the specific context and requirements of the project.

2023-06-14 21:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        boolean userIsItemOwner = item.getOwner().getId().equals(userId);
isUserItemOwner было бы чуть грамотней, поскольку эта переменная boolean, 
в таком случае ответ на ее назавние будет true или false

2023-06-14 21:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Sort sortStarts = Sort.by("start").ascending();
хорошее вынесение всего необходимого в локальные переменные

2023-06-14 21:26 UTC, ebogacheva commented on pom.xml
>  	</dependencies>
Нужно было что-то еще, кроме: 
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<scope>runtime</scope>
		</dependency>
?

2023-06-14 21:28 UTC, ebogacheva commented on pom.xml
> +			<artifactId>hibernate-core</artifactId>
Убрала.

2023-06-14 21:28 UTC, ebogacheva commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingFullDto update(@RequestHeader("X-Sharer-User-Id") long userId,
Сделано.

2023-06-14 21:52 UTC, ebogacheva commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        getUserIfExists(userId);
Сделано.

2023-06-15 01:25 UTC, ebogacheva commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            }
Мне тоже это не нравилось. 
Но я очень не люблю (визуально) как выглядит и "читается" switch-case (нервирует от меня, это личное восприятие). Поэтому всегда стараюсь его заменить чем-нибудь. Не всегда удачно. 

Переделала еще раз. 
В этом варианте мне не нравится, что я хардкожу значение BookingStatus в репозитории:
    String GET_WAITING = " and b.status = ru.practicum.shareit.booking.model.BookingStatus.WAITING ";
    String GET_REJECTED = " and b.status = ru.practicum.shareit.booking.model.BookingStatus.REJECTED ";

Если так тоже не очень, то сдамся и сделаю switch-case))

2023-06-15 08:42 UTC, ebogacheva commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        public abstract List<Booking> getUserBookings(BookingRepository repository, Long userId);
Абстрактные методы ликвидировала, в енаме - только значения.

2023-06-15 08:44 UTC, ebogacheva commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        boolean userIsItemOwner = item.getOwner().getId().equals(userId);
Сделала. Каждый раз мучаюсь с названиями boolean.

2023-06-15 08:54 UTC, ebogacheva commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (booking.getStatus().equals(BookingStatus.APPROVED)) {
Ок

2023-06-15 19:59 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        boolean userIsItemOwner = item.getOwner().getId().equals(userId);
не ты одна) еще примерно каждый программист))

2023-06-15 20:00 UTC, Fleaman777 commented on pom.xml
>  	</dependencies>
ну да, все в порядке, есть. в 1м ревью не заметил

2023-06-15 20:17 UTC, Fleaman777 approved these changes

2023-06-15 20:17 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        }
что бы чуть упросить эту инициализацию мапы, можно использовать фабричный метод Map.of(....)
а так же добавить статический импорт для енам значений (не указывать SearchCondition), т.к. и без SearchCondition будет понятно о чем эти значения енама

2023-06-15 20:17 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    private final Map<SearchCondition, Function<Long, List<Booking>>> conditions = new HashMap<>();
молодец, не самым тривиальным, но очень хорошим подходом пошла, в паттернах программирования этот подход называется Стратегия

2023-06-15 20:17 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            }
ну да, я согласен, не все однозначно со switch, 
слышал разные мнения по его применению, кому-то он нравится, кто-то лучше напишет через if else, 

как альтернатива, это сделать через Map, что в принципе ты здорово и реализовала. 

в относительно новой джаве, в 17, switch улучшили, теперь он работает как паттерн матчинг
https://www.baeldung.com/java-switch-pattern-matching
что в целом визуально довольно неплохо выглдяит, ну и по производительности у него есть некоторые улучшения

2023-06-15 21:04 UTC, merged