Add item requests
ebogacheva/java-shareit pull request #3
Opened 2023-06-29 12:54 UTC by ebogacheva

2023-07-01 06:33 UTC, Fleaman777 requested changes

2023-07-01 06:33 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +        List<Item> items = pageOfItems.getContent();
в этом случае можно было бы не выносить pageOfItems.getContent() в отдельную переменную, а сразу вызвать на этом стрим
т.е. сделать 
return pageOfItems.getContent().stream....

2023-07-01 06:33 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    public RequestWithItemsDto create(ItemRequestInputDto itemRequestInputDto, Long userId) {
метод изменяет состояние БД, правильней было бы его выполнять в транзакции,

2023-07-01 06:33 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +    }
хороший метод с beforeEach, 
выполняет всю необходимую инициализацию перед тестами

2023-07-01 06:33 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +    private void changeBookingStatus(Booking booking, BookingStatus status) {
в тестах тоже хорошо бы придерживаться порядка методов,
сначла public, потом private

2023-07-01 06:33 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingServiceRepositoryIntegrationTest.java
> +        if (actualBooking.isPresent()) {
по хорошему, в тестах не должно быть условий, т.к. в тестах четко задано, что выолняется и какой будет результат

2023-07-01 06:33 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/item/mapper/ItemMapperTest.java
> +}
хорошо было бы заполнить эти тесты

2023-07-01 06:33 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/item/repository/ItemRepositoryTest.java
> +    ItemRequestRepository requestRepository;
если нет какого-то замысла, почему эти поля должны иметь default модификатор доступа, то лучше сделать private. 
что бы придерживаться единого стиля написания различных классов

2023-07-01 06:33 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +package ru.practicum.shareit.booking;
для более удобной навигации по Booking тестам, их так же можно разместить по соответствуюзим подпакетам 
service/controller....

2023-07-02 23:43 UTC, ebogacheva commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +        List<Item> items = pageOfItems.getContent();
Сделала.

2023-07-02 23:45 UTC, ebogacheva commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    public RequestWithItemsDto create(ItemRequestInputDto itemRequestInputDto, Long userId) {
Да, сделала.

2023-07-02 23:46 UTC, ebogacheva commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +    private void changeBookingStatus(Booking booking, BookingStatus status) {
Навела порядок.

2023-07-02 23:48 UTC, ebogacheva commented on src/test/java/ru/practicum/shareit/booking/BookingServiceRepositoryIntegrationTest.java
> +        if (actualBooking.isPresent()) {
Переделала все места с Optional на проверку, что Optional is Present.

2023-07-03 00:01 UTC, ebogacheva commented on src/test/java/ru/practicum/shareit/item/mapper/ItemMapperTest.java
> +}
Вот что значит сгенерить тесты сразу для всех классов) добавила.

2023-07-03 11:14 UTC, ebogacheva commented on src/test/java/ru/practicum/shareit/item/repository/ItemRepositoryTest.java
> +    ItemRequestRepository requestRepository;
модификаторы доступа поправила во всех тестовых классах

2023-07-03 11:40 UTC, ebogacheva commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +package ru.practicum.shareit.booking;
унифицировала подпакеты для всего проекта, включая тесты

2023-07-03 19:04 UTC, Fleaman777 approved these changes

2023-07-03 19:22 UTC, merged