Add-docker
ebogacheva/java-shareit pull request #4
Opened 2023-07-05 11:58 UTC by ebogacheva

2023-07-06 20:12 UTC, Fleaman777 requested changes

2023-07-06 20:12 UTC, Fleaman777 commented on docker-compose.yml
> +    image: postgres:13.7-alpine
хорошо, что указываешь конкретную версию имеджа, а не просто latest,
так безопасней, т.к. меньше шансов нарваться на версию базового имеджа, с которым текущая версия приложения не будет работать,
то же относится и к Dockerfile

2023-07-06 20:12 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    }
а нужны ли, по сути, 3 идентичных эксепшен хэндлера,
можно просто настроить 1 метод что бы он ловил все эксепшены

2023-07-06 20:12 UTC, Fleaman777 commented on gateway/src/main/resources/application.properties
> +shareit-server.url=http://localhost:9090
сейчас получается, что значения переменных окружения, используются те, которые указаны в application.properties, а не те, которые в docker-compose
например в application.properties ,можно использовать такую конструкцию: 
shareit-server.url=${SHAREIT_SERVER_URL:http://localhost:9090}
она означает, что если, в докер-компосе не просетать переменную SHAREIT_SERVER_URL, то будет использоваться дефлотное значение http://localhost:9090

2023-07-06 20:12 UTC, Fleaman777 commented on server/src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
здесь можно было бы добавить переменную SPRING_DATASOURCE_URL, что бы явно было ее видно

2023-07-07 15:18 UTC, ebogacheva commented on gateway/src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    }
Тесты в постмане, которые мы проходим, хотят специфический формат от ошибки в state. Два другие хэндлера объединила.

2023-07-07 15:42 UTC, ebogacheva commented on gateway/src/main/resources/application.properties
> +shareit-server.url=http://localhost:9090
Сделала.

2023-07-07 16:16 UTC, ebogacheva commented on server/src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
Добавила

2023-07-07 20:32 UTC, Fleaman777 approved these changes

2023-07-07 21:01 UTC, merged